export const wordsAlphabet = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
];
export const introwords = ["Word", "Scramble"];
export const samples = [
  {
    id: 1,
    meaning: "to show that you are happy or that you think something is funny",
    word: "ulgah",
    rightword: "laugh",
  },
  {
    id: 2,
    meaning: "to be in the state of rest when your eyes are closed",
    word: "eslpe",
    rightword: "sleep",
  },
  {
    id: 3,
    meaning: "a place where children go to be educated",
    word: "ohocsl",
    rightword: "school",
  },
  {
    id: 4,
    meaning: "a man who is about to get married or just got married",
    word: "ogomr",
    rightword: "groom",
  },
  {
    id: 5,
    meaning: "an action or activity that is against the law",
    word: "meicr",
    rightword: "crime",
  },
  {
    id: 6,
    meaning: "unable to hear, either completely or partly",
    word: "fdea",
    rightword: "deaf",
  },
  {
    id: 7,
    meaning: "the lowest point or part of something",
    word: "tombot",
    rightword: "bottom",
  },
  {
    id: 8,
    meaning:
      "something that you want to happen very much but that is not very likely",
    word: "remda",
    rightword: "dream",
  },
  {
    id: 9,
    meaning: "food made of flour, water, and yeast mixed together and baked",
    word: "debra",
    rightword: "bread",
  },
  {
    id: 10,
    meaning: "to hit someone or something with your fist",
    word: "hnucp",
    rightword: "punch",
  },
];
